"use client";

import { useState, useEffect } from "react";
import Navbar from "./Components/Navbar";
import Sidebar from "./Components/Sidebar";
import ProjectForm from "./Components/ProjectForm";

export default function Page() {
  const [history, setHistory] = useState([]);
  const [selectedProject, setSelectedProject] = useState(null);
  const [loading, setLoading] = useState(true);

  // Fetch existing projects on mount
  useEffect(() => {
    const fetchProjects = async () => {
      try {
        const res = await fetch("/api/project");
        const data = await res.json();
        
        if (data.projects) {
          const formattedProjects = data.projects.map(project => ({
            title: `${project.branch} Project` || "Untitled Project",
            content: project.result || "",
            _id: project._id,
            branch: project.branch,
            skills: project.skills,
            time: project.time,
          }));
          setHistory(formattedProjects);
        }
      } catch (error) {
        console.error("Error fetching projects:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchProjects();
  }, []);

  return (
    <div className="flex flex-col h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-red-50">
      {/* Animated background blobs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-red-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
      </div>

      <Navbar />

      <div className="flex flex-1 overflow-hidden relative z-10">
        {/* Sidebar */}
        <Sidebar history={history} setSelected={setSelectedProject} />

        {/* Main Content */}
        <div className="flex-1 p-6 overflow-y-auto">
          {loading ? (
            <div className="flex items-center justify-center h-full">
              <div className="text-center">
                <div className="inline-block animate-spin rounded-full h-12 w-12 border-4 border-purple-500 border-t-transparent"></div>
                <p className="mt-4 text-gray-600 font-medium">Loading projects...</p>
              </div>
            </div>
          ) : (
            <div className="max-w-6xl mx-auto space-y-6">
            {/* Welcome Section */}
            {!selectedProject && history.length === 0 && (
              <div className="text-center py-12 mb-6">
                <div className="text-7xl mb-4 animate-bounce">✨</div>
                <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-purple-600 via-pink-600 to-red-600 bg-clip-text text-transparent mb-4">
                  Welcome to ProjectGenie
                </h1>
                <p className="text-gray-600 text-lg max-w-2xl mx-auto">
                  Generate innovative AI-powered project ideas tailored to your skills, branch, and timeline
                </p>
              </div>
            )}

            {/* Project Form */}
            <ProjectForm
              setHistory={setHistory}
              setSelected={setSelectedProject}
            />

            {/* Selected Project Display */}
            {selectedProject && (
              <div className="bg-white/80 backdrop-blur-xl p-8 rounded-2xl shadow-2xl border border-white/20 animate-fadeIn">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h3 className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                      {selectedProject.title}
                    </h3>
                    <p className="text-sm text-gray-500 mt-1">Generated by ProjectGenie AI</p>
                  </div>
                  <button
                    onClick={() => setSelectedProject(null)}
                    className="text-gray-400 hover:text-gray-600 transition-colors"
                  >
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
                
                <div className="prose prose-purple max-w-none">
                  <div className="whitespace-pre-wrap text-gray-700 leading-relaxed">
                    {selectedProject.content}
                  </div>
                </div>

                <div className="mt-6 flex gap-3">
                  <button 
                    onClick={() => {
                      navigator.clipboard.writeText(selectedProject.content);
                      alert('Copied to clipboard!');
                    }}
                    className="px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-semibold hover:from-purple-700 hover:to-pink-700 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105"
                  >
                    📋 Copy to Clipboard
                  </button>
                  <button className="px-6 py-3 bg-white border-2 border-purple-200 text-purple-600 rounded-lg font-semibold hover:bg-purple-50 transition-all duration-300">
                    💾 Save Project
                  </button>
                </div>
              </div>
            )}

            {/* Stats Cards - Show when there's history */}
            {history.length > 0 && !selectedProject && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
                <div className="bg-white/80 backdrop-blur-xl p-6 rounded-2xl shadow-xl border border-white/20">
                  <div className="text-3xl mb-2">🎯</div>
                  <div className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                    {history.length}
                  </div>
                  <div className="text-gray-600 font-medium">Projects Generated</div>
                </div>
                
                <div className="bg-white/80 backdrop-blur-xl p-6 rounded-2xl shadow-xl border border-white/20">
                  <div className="text-3xl mb-2">💡</div>
                  <div className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                    AI
                  </div>
                  <div className="text-gray-600 font-medium">Powered Ideas</div>
                </div>
                
                <div className="bg-white/80 backdrop-blur-xl p-6 rounded-2xl shadow-xl border border-white/20">
                  <div className="text-3xl mb-2">⚡</div>
                  <div className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                    Fast
                  </div>
                  <div className="text-gray-600 font-medium">Generation Speed</div>
                </div>
              </div>
            )}
            </div>
          )}
        </div>
      </div>

      <style jsx global>{`
        @keyframes blob {
          0%, 100% {
            transform: translate(0, 0) scale(1);
          }
          33% {
            transform: translate(30px, -50px) scale(1.1);
          }
          66% {
            transform: translate(-20px, 20px) scale(0.9);
          }
        }

        .animate-blob {
          animation: blob 7s infinite;
        }

        .animation-delay-2000 {
          animation-delay: 2s;
        }

        .animation-delay-4000 {
          animation-delay: 4s;
        }

        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .animate-fadeIn {
          animation: fadeIn 0.5s ease-out;
        }
      `}</style>
    </div>
  );
}